apiVersion: v1
kind: Service
metadata:
  name: fastapi-yolo-service
spec:
  selector:
    app: fastapi-food-seg
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
